language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php -v
  - vendor/bin/phpunit -c tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
